# ==========================================================
# Copyright (c) 2026 MissShikhamusicbot
# All Rights Reserved.
#
# Project      : MissShikhamusicbot
# Powered By   : MissShikhamusicbot
# Type         : API Based Telegram Music Bot
#
# Bot          : @MissShikhaMusicBot
#
# Unauthorized copying, modification, or redistribution
# of this source code without permission is prohibited.
# ==========================================================
services:
  - type: worker
    name: missshikhamusicbot
    runtime: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python -m Elevenyts
    plan: free
